### PR TITLE
Initial Setup

### LINKED ISSUE #6: Initial Setup
### Outcome

Create the initial file structure and add the base node js dependencies. 

### Moment

The initial file structure and base dependencies - Other dependencies can be added as required

### Key Results

- [x] Create file structure
- [x] Setup Prettier
- [x] Setup .gitignore
- [x] Add dependencies

### PR DESCRIPTION
**Pull request by luke-mccallum**
initial frontend set up using Create React App, open to review or suggestions for alternative templates

### CODE REVIEW

**Comment by pumbas600** [comment]
Feel free to change the backend file structure if you guys want :)

**Comment by luke-mccallum** [comment]
frontend is ready for review with basic file structure established

**Review by lpar105 — APPROVED** [review]
I've only really been able to view the back-end side of things but this looks good to me! 

(I don't have super in depth understanding of what's going on in the front-end, so if the other reviewers could focus on that that would be great :))

As a side note, do we want to require eslint and get everyone set up with the same config file so we are on the same page in a similar vein to having the prettier config supplied?

**Comment by pumbas600** [comment]
Yeah, I think requiring eslint is a good idea. I'll try and get that setup :)

**Comment by pumbas600** [comment]
> Yeah, I think requiring eslint is a good idea. I'll try and get that setup :)

So I was unable to create a single eslint file in the root of the project as the package.json files are in subfolders, so I had to create 2 separate ones.

I think it may be better though, to create a 3rd "common" package.json at the root of the project where we can put all the shared dependencies, e.g: Typescript, Eslint, Prettier.

What do y'all think @luke-mccallum @lpar105

**Comment by lpar105** [comment]
Common would be nicer in the long run if it's easy enough to implement :)

**Comment by pumbas600** [comment]
Yeah, it's easy to do, the only annoying thing is it means you'll also have to do `npm i` in the root directory and the `backend` folder. Fortunately, you'll probably only have to do this once as it's unlikely we'll add many (if any) new shared dependencies.

Still, it might be nice just to be able to have one shared eslint config file

**Comment by luke-mccallum** [comment]
having to do npm i in both the root and frontend/backend isn't an issue if we only have to do it once

**Review by long715 — APPROVED** [review]
Looks good!

**Pull request merged**
